package spirv.enumerants;

import spirv.instructions.ValueEnum;

public enum Capability implements ValueEnum {
	MATRIX(0),
	SHADER(1),
	GEOMETRY(2),
	TESSELLATION(3),
	ADDRESSES(4),
	LINKAGE(5),
	KERNEL(6),
	VECTOR16(7),
	FLOAT16_BUFFER(8),
	FLOAT16(9),
	FLOAT64(10),
	INT64(11),
	INT64_ATOMICS(12),
	IMAGE_BASIC(13),
	IMAGE_READ_WRITE(14),
	IMAGE_MIPMAP(15),
	PIPES(17),
	GROUPS(18),
	DEVICE_ENQUEUE(19),
	LITERAL_SAMPLER(20),
	ATOMIC_STORAGE(21),
	INT16(22),
	TESSELLATION_POINT_SIZE(23),
	GEOMETRY_POINT_SIZE(24),
	IMAGE_GATHER_EXTENDED(25),
	STORAGE_IMAGE_MULTISAMPLE(27),
	UNIFORM_BUFFER_ARRAY_DYNAMIC_INDEXING(28),
	SAMPLED_IMAGE_ARRAY_DYNAMIC_INDEXING(29),
	STORAGE_BUFFER_ARRAY_DYNAMIC_INDEXING(30),
	STORAGE_IMAGE_ARRAY_DYNAMIC_INDEXING(31),
	CLIP_DISTANCE(32),
	CULL_DISTANCE(33),
	IMAGE_CUBE_ARRAY(34),
	SAMPLE_RATE_SHADING(35),
	IMAGE_RECT(36),
	SAMPLED_RECT(37),
	GENERIC_POINTER(38),
	INT8(39),
	INPUT_ATTACHMENT(40),
	SPARSE_RESIDENCY(41),
	MIN_LOD(42),
	SAMPLED1D(43),
	IMAGE1D(44),
	SAMPLED_CUBE_ARRAY(45),
	SAMPLED_BUFFER(46),
	IMAGE_BUFFER(47),
	IMAGE_MS_ARRAY(48),
	STORAGE_IMAGE_EXTENDED_FORMATS(49),
	IMAGE_QUERY(50),
	DERIVATIVE_CONTROL(51),
	INTERPOLATION_FUNCTION(52),
	TRANSFORM_FEEDBACK(53),
	GEOMETRY_STREAMS(54),
	STORAGE_IMAGE_READ_WITHOUT_FORMAT(55),
	STORAGE_IMAGE_WRITE_WITHOUT_FORMAT(56),
	MULTI_VIEWPORT(57),
	SUBGROUP_DISPATCH(58),
	NAMED_BARRIER(59),
	PIPE_STORAGE(60),
	GROUP_NON_UNIFORM(61),
	GROUP_NON_UNIFORM_VOTE(62),
	GROUP_NON_UNIFORM_ARITHMETIC(63),
	GROUP_NON_UNIFORM_BALLOT(64),
	GROUP_NON_UNIFORM_SHUFFLE(65),
	GROUP_NON_UNIFORM_SHUFFLE_RELATIVE(66),
	GROUP_NON_UNIFORM_CLUSTERED(67),
	GROUP_NON_UNIFORM_QUAD(68),
	SHADER_LAYER(69),
	SHADER_VIEWPORT_INDEX(70),
	UNIFORM_DECORATION(71),
	CORE_BUILTINS_ARM(4165),
	TILE_IMAGE_COLOR_READ_ACCESS_EXT(4166),
	TILE_IMAGE_DEPTH_READ_ACCESS_EXT(4167),
	TILE_IMAGE_STENCIL_READ_ACCESS_EXT(4168),
	TENSORS_ARM(4174),
	STORAGE_TENSOR_ARRAY_DYNAMIC_INDEXING_ARM(4175),
	STORAGE_TENSOR_ARRAY_NON_UNIFORM_INDEXING_ARM(4176),
	GRAPH_ARM(4191),
	COOPERATIVE_MATRIX_LAYOUTS_ARM(4201),
	FLOAT8EXT(4212),
	FLOAT8_COOPERATIVE_MATRIX_EXT(4213),
	FRAGMENT_SHADING_RATE_KHR(4422),
	SUBGROUP_BALLOT_KHR(4423),
	DRAW_PARAMETERS(4427),
	WORKGROUP_MEMORY_EXPLICIT_LAYOUT_KHR(4428),
	WORKGROUP_MEMORY_EXPLICIT_LAYOUT8_BIT_ACCESS_KHR(4429),
	WORKGROUP_MEMORY_EXPLICIT_LAYOUT16_BIT_ACCESS_KHR(4430),
	SUBGROUP_VOTE_KHR(4431),
	STORAGE_BUFFER16_BIT_ACCESS(4433),
	UNIFORM_AND_STORAGE_BUFFER16_BIT_ACCESS(4434),
	STORAGE_PUSH_CONSTANT16(4435),
	STORAGE_INPUT_OUTPUT16(4436),
	DEVICE_GROUP(4437),
	MULTI_VIEW(4439),
	VARIABLE_POINTERS_STORAGE_BUFFER(4441),
	VARIABLE_POINTERS(4442),
	ATOMIC_STORAGE_OPS(4445),
	SAMPLE_MASK_POST_DEPTH_COVERAGE(4447),
	STORAGE_BUFFER8_BIT_ACCESS(4448),
	UNIFORM_AND_STORAGE_BUFFER8_BIT_ACCESS(4449),
	STORAGE_PUSH_CONSTANT8(4450),
	DENORM_PRESERVE(4464),
	DENORM_FLUSH_TO_ZERO(4465),
	SIGNED_ZERO_INF_NAN_PRESERVE(4466),
	ROUNDING_MODE_RTE(4467),
	ROUNDING_MODE_RTZ(4468),
	RAY_QUERY_PROVISIONAL_KHR(4471),
	RAY_QUERY_KHR(4472),
	UNTYPED_POINTERS_KHR(4473),
	RAY_TRAVERSAL_PRIMITIVE_CULLING_KHR(4478),
	RAY_TRACING_KHR(4479),
	TEXTURE_SAMPLE_WEIGHTED_QCOM(4484),
	TEXTURE_BOX_FILTER_QCOM(4485),
	TEXTURE_BLOCK_MATCH_QCOM(4486),
	TILE_SHADING_QCOM(4495),
	COOPERATIVE_MATRIX_CONVERSION_QCOM(4496),
	TEXTURE_BLOCK_MATCH2QCOM(4498),
	FLOAT16_IMAGE_AMD(5008),
	IMAGE_GATHER_BIAS_LOD_AMD(5009),
	FRAGMENT_MASK_AMD(5010),
	STENCIL_EXPORT_EXT(5013),
	IMAGE_READ_WRITE_LOD_AMD(5015),
	INT64_IMAGE_EXT(5016),
	SHADER_CLOCK_KHR(5055),
	SHADER_ENQUEUE_AMDX(5067),
	QUAD_CONTROL_KHR(5087),
	INT4_TYPE_INTEL(5112),
	INT4_COOPERATIVE_MATRIX_INTEL(5114),
	B_FLOAT16_TYPE_KHR(5116),
	B_FLOAT16_DOT_PRODUCT_KHR(5117),
	B_FLOAT16_COOPERATIVE_MATRIX_KHR(5118),
	SAMPLE_MASK_OVERRIDE_COVERAGE_NV(5249),
	GEOMETRY_SHADER_PASSTHROUGH_NV(5251),
	SHADER_VIEWPORT_INDEX_LAYER_EXT(5254),
	SHADER_VIEWPORT_MASK_NV(5255),
	SHADER_STEREO_VIEW_NV(5259),
	PER_VIEW_ATTRIBUTES_NV(5260),
	FRAGMENT_FULLY_COVERED_EXT(5265),
	MESH_SHADING_NV(5266),
	IMAGE_FOOTPRINT_NV(5282),
	MESH_SHADING_EXT(5283),
	FRAGMENT_BARYCENTRIC_KHR(5284),
	COMPUTE_DERIVATIVE_GROUP_QUADS_KHR(5288),
	FRAGMENT_DENSITY_EXT(5291),
	GROUP_NON_UNIFORM_PARTITIONED_NV(5297),
	SHADER_NON_UNIFORM(5301),
	RUNTIME_DESCRIPTOR_ARRAY(5302),
	INPUT_ATTACHMENT_ARRAY_DYNAMIC_INDEXING(5303),
	UNIFORM_TEXEL_BUFFER_ARRAY_DYNAMIC_INDEXING(5304),
	STORAGE_TEXEL_BUFFER_ARRAY_DYNAMIC_INDEXING(5305),
	UNIFORM_BUFFER_ARRAY_NON_UNIFORM_INDEXING(5306),
	SAMPLED_IMAGE_ARRAY_NON_UNIFORM_INDEXING(5307),
	STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING(5308),
	STORAGE_IMAGE_ARRAY_NON_UNIFORM_INDEXING(5309),
	INPUT_ATTACHMENT_ARRAY_NON_UNIFORM_INDEXING(5310),
	UNIFORM_TEXEL_BUFFER_ARRAY_NON_UNIFORM_INDEXING(5311),
	STORAGE_TEXEL_BUFFER_ARRAY_NON_UNIFORM_INDEXING(5312),
	RAY_TRACING_POSITION_FETCH_KHR(5336),
	RAY_TRACING_NV(5340),
	RAY_TRACING_MOTION_BLUR_NV(5341),
	VULKAN_MEMORY_MODEL(5345),
	VULKAN_MEMORY_MODEL_DEVICE_SCOPE(5346),
	PHYSICAL_STORAGE_BUFFER_ADDRESSES(5347),
	COMPUTE_DERIVATIVE_GROUP_LINEAR_KHR(5350),
	RAY_TRACING_PROVISIONAL_KHR(5353),
	COOPERATIVE_MATRIX_NV(5357),
	FRAGMENT_SHADER_SAMPLE_INTERLOCK_EXT(5363),
	FRAGMENT_SHADER_SHADING_RATE_INTERLOCK_EXT(5372),
	SHADER_SM_BUILTINS_NV(5373),
	FRAGMENT_SHADER_PIXEL_INTERLOCK_EXT(5378),
	DEMOTE_TO_HELPER_INVOCATION(5379),
	DISPLACEMENT_MICROMAP_NV(5380),
	RAY_TRACING_OPACITY_MICROMAP_EXT(5381),
	SHADER_INVOCATION_REORDER_NV(5383),
	BINDLESS_TEXTURE_NV(5390),
	RAY_QUERY_POSITION_FETCH_KHR(5391),
	COOPERATIVE_VECTOR_NV(5394),
	ATOMIC_FLOAT16_VECTOR_NV(5404),
	RAY_TRACING_DISPLACEMENT_MICROMAP_NV(5409),
	RAW_ACCESS_CHAINS_NV(5414),
	RAY_TRACING_SPHERES_GEOMETRY_NV(5418),
	RAY_TRACING_LINEAR_SWEPT_SPHERES_GEOMETRY_NV(5419),
	COOPERATIVE_MATRIX_REDUCTIONS_NV(5430),
	COOPERATIVE_MATRIX_CONVERSIONS_NV(5431),
	COOPERATIVE_MATRIX_PER_ELEMENT_OPERATIONS_NV(5432),
	COOPERATIVE_MATRIX_TENSOR_ADDRESSING_NV(5433),
	COOPERATIVE_MATRIX_BLOCK_LOADS_NV(5434),
	COOPERATIVE_VECTOR_TRAINING_NV(5435),
	RAY_TRACING_CLUSTER_ACCELERATION_STRUCTURE_NV(5437),
	TENSOR_ADDRESSING_NV(5439),
	SUBGROUP_SHUFFLE_INTEL(5568),
	SUBGROUP_BUFFER_BLOCK_IOINTEL(5569),
	SUBGROUP_IMAGE_BLOCK_IOINTEL(5570),
	SUBGROUP_IMAGE_MEDIA_BLOCK_IOINTEL(5579),
	ROUND_TO_INFINITY_INTEL(5582),
	FLOATING_POINT_MODE_INTEL(5583),
	INTEGER_FUNCTIONS2INTEL(5584),
	FUNCTION_POINTERS_INTEL(5603),
	INDIRECT_REFERENCES_INTEL(5604),
	ASM_INTEL(5606),
	ATOMIC_FLOAT32_MIN_MAX_EXT(5612),
	ATOMIC_FLOAT64_MIN_MAX_EXT(5613),
	ATOMIC_FLOAT16_MIN_MAX_EXT(5616),
	VECTOR_COMPUTE_INTEL(5617),
	VECTOR_ANY_INTEL(5619),
	EXPECT_ASSUME_KHR(5629),
	SUBGROUP_AVC_MOTION_ESTIMATION_INTEL(5696),
	SUBGROUP_AVC_MOTION_ESTIMATION_INTRA_INTEL(5697),
	SUBGROUP_AVC_MOTION_ESTIMATION_CHROMA_INTEL(5698),
	VARIABLE_LENGTH_ARRAY_INTEL(5817),
	FUNCTION_FLOAT_CONTROL_INTEL(5821),
	FPGA_MEMORY_ATTRIBUTES_INTEL(5824),
	FP_FAST_MATH_MODE_INTEL(5837),
	ARBITRARY_PRECISION_INTEGERS_INTEL(5844),
	ARBITRARY_PRECISION_FLOATING_POINT_INTEL(5845),
	UNSTRUCTURED_LOOP_CONTROLS_INTEL(5886),
	FPGA_LOOP_CONTROLS_INTEL(5888),
	KERNEL_ATTRIBUTES_INTEL(5892),
	FPGA_KERNEL_ATTRIBUTES_INTEL(5897),
	FPGA_MEMORY_ACCESSES_INTEL(5898),
	FPGA_CLUSTER_ATTRIBUTES_INTEL(5904),
	LOOP_FUSE_INTEL(5906),
	FPGADSP_CONTROL_INTEL(5908),
	MEMORY_ACCESS_ALIASING_INTEL(5910),
	FPGA_INVOCATION_PIPELINING_ATTRIBUTES_INTEL(5916),
	FPGA_BUFFER_LOCATION_INTEL(5920),
	ARBITRARY_PRECISION_FIXED_POINT_INTEL(5922),
	USM_STORAGE_CLASSES_INTEL(5935),
	RUNTIME_ALIGNED_ATTRIBUTE_INTEL(5939),
	IO_PIPES_INTEL(5943),
	BLOCKING_PIPES_INTEL(5945),
	FPGA_REG_INTEL(5948),
	DOT_PRODUCT_INPUT_ALL(6016),
	DOT_PRODUCT_INPUT4X8_BIT(6017),
	DOT_PRODUCT_INPUT4X8_BIT_PACKED(6018),
	DOT_PRODUCT(6019),
	RAY_CULL_MASK_KHR(6020),
	COOPERATIVE_MATRIX_KHR(6022),
	REPLICATED_COMPOSITES_EXT(6024),
	BIT_INSTRUCTIONS(6025),
	GROUP_NON_UNIFORM_ROTATE_KHR(6026),
	FLOAT_CONTROLS2(6029),
	ATOMIC_FLOAT32_ADD_EXT(6033),
	ATOMIC_FLOAT64_ADD_EXT(6034),
	LONG_COMPOSITES_INTEL(6089),
	OPT_NONE_EXT(6094),
	ATOMIC_FLOAT16_ADD_EXT(6095),
	DEBUG_INFO_MODULE_INTEL(6114),
	B_FLOAT16_CONVERSION_INTEL(6115),
	SPLIT_BARRIER_INTEL(6141),
	ARITHMETIC_FENCE_EXT(6144),
	FPGA_CLUSTER_ATTRIBUTES_V2INTEL(6150),
	FPGA_KERNEL_ATTRIBUTESV2INTEL(6161),
	TASK_SEQUENCE_INTEL(6162),
	FP_MAX_ERROR_INTEL(6169),
	FPGA_LATENCY_CONTROL_INTEL(6171),
	FPGA_ARGUMENT_INTERFACES_INTEL(6174),
	GLOBAL_VARIABLE_HOST_ACCESS_INTEL(6187),
	GLOBAL_VARIABLE_FPGA_DECORATIONS_INTEL(6189),
	SUBGROUP_BUFFER_PREFETCH_INTEL(6220),
	SUBGROUP2D_BLOCK_IOINTEL(6228),
	SUBGROUP2D_BLOCK_TRANSFORM_INTEL(6229),
	SUBGROUP2D_BLOCK_TRANSPOSE_INTEL(6230),
	SUBGROUP_MATRIX_MULTIPLY_ACCUMULATE_INTEL(6236),
	TERNARY_BITWISE_FUNCTION_INTEL(6241),
	SPEC_CONDITIONAL_INTEL(6245),
	FUNCTION_VARIANTS_INTEL(6246),
	GROUP_UNIFORM_ARITHMETIC_KHR(6400),
	TENSOR_FLOAT32_ROUNDING_INTEL(6425),
	MASKED_GATHER_SCATTER_INTEL(6427),
	CACHE_CONTROLS_INTEL(6441),
	REGISTER_LIMITS_INTEL(6460),
	BINDLESS_IMAGES_INTEL(6528);

	public static final Capability[] VALUES = Capability.values();

	public final int value;

	Capability(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	public static Capability get(int value) {
		switch (value) {
			case 0:
				return Capability.MATRIX;
			case 1:
				return Capability.SHADER;
			case 2:
				return Capability.GEOMETRY;
			case 3:
				return Capability.TESSELLATION;
			case 4:
				return Capability.ADDRESSES;
			case 5:
				return Capability.LINKAGE;
			case 6:
				return Capability.KERNEL;
			case 7:
				return Capability.VECTOR16;
			case 8:
				return Capability.FLOAT16_BUFFER;
			case 9:
				return Capability.FLOAT16;
			case 10:
				return Capability.FLOAT64;
			case 11:
				return Capability.INT64;
			case 12:
				return Capability.INT64_ATOMICS;
			case 13:
				return Capability.IMAGE_BASIC;
			case 14:
				return Capability.IMAGE_READ_WRITE;
			case 15:
				return Capability.IMAGE_MIPMAP;
			case 17:
				return Capability.PIPES;
			case 18:
				return Capability.GROUPS;
			case 19:
				return Capability.DEVICE_ENQUEUE;
			case 20:
				return Capability.LITERAL_SAMPLER;
			case 21:
				return Capability.ATOMIC_STORAGE;
			case 22:
				return Capability.INT16;
			case 23:
				return Capability.TESSELLATION_POINT_SIZE;
			case 24:
				return Capability.GEOMETRY_POINT_SIZE;
			case 25:
				return Capability.IMAGE_GATHER_EXTENDED;
			case 27:
				return Capability.STORAGE_IMAGE_MULTISAMPLE;
			case 28:
				return Capability.UNIFORM_BUFFER_ARRAY_DYNAMIC_INDEXING;
			case 29:
				return Capability.SAMPLED_IMAGE_ARRAY_DYNAMIC_INDEXING;
			case 30:
				return Capability.STORAGE_BUFFER_ARRAY_DYNAMIC_INDEXING;
			case 31:
				return Capability.STORAGE_IMAGE_ARRAY_DYNAMIC_INDEXING;
			case 32:
				return Capability.CLIP_DISTANCE;
			case 33:
				return Capability.CULL_DISTANCE;
			case 34:
				return Capability.IMAGE_CUBE_ARRAY;
			case 35:
				return Capability.SAMPLE_RATE_SHADING;
			case 36:
				return Capability.IMAGE_RECT;
			case 37:
				return Capability.SAMPLED_RECT;
			case 38:
				return Capability.GENERIC_POINTER;
			case 39:
				return Capability.INT8;
			case 40:
				return Capability.INPUT_ATTACHMENT;
			case 41:
				return Capability.SPARSE_RESIDENCY;
			case 42:
				return Capability.MIN_LOD;
			case 43:
				return Capability.SAMPLED1D;
			case 44:
				return Capability.IMAGE1D;
			case 45:
				return Capability.SAMPLED_CUBE_ARRAY;
			case 46:
				return Capability.SAMPLED_BUFFER;
			case 47:
				return Capability.IMAGE_BUFFER;
			case 48:
				return Capability.IMAGE_MS_ARRAY;
			case 49:
				return Capability.STORAGE_IMAGE_EXTENDED_FORMATS;
			case 50:
				return Capability.IMAGE_QUERY;
			case 51:
				return Capability.DERIVATIVE_CONTROL;
			case 52:
				return Capability.INTERPOLATION_FUNCTION;
			case 53:
				return Capability.TRANSFORM_FEEDBACK;
			case 54:
				return Capability.GEOMETRY_STREAMS;
			case 55:
				return Capability.STORAGE_IMAGE_READ_WITHOUT_FORMAT;
			case 56:
				return Capability.STORAGE_IMAGE_WRITE_WITHOUT_FORMAT;
			case 57:
				return Capability.MULTI_VIEWPORT;
			case 58:
				return Capability.SUBGROUP_DISPATCH;
			case 59:
				return Capability.NAMED_BARRIER;
			case 60:
				return Capability.PIPE_STORAGE;
			case 61:
				return Capability.GROUP_NON_UNIFORM;
			case 62:
				return Capability.GROUP_NON_UNIFORM_VOTE;
			case 63:
				return Capability.GROUP_NON_UNIFORM_ARITHMETIC;
			case 64:
				return Capability.GROUP_NON_UNIFORM_BALLOT;
			case 65:
				return Capability.GROUP_NON_UNIFORM_SHUFFLE;
			case 66:
				return Capability.GROUP_NON_UNIFORM_SHUFFLE_RELATIVE;
			case 67:
				return Capability.GROUP_NON_UNIFORM_CLUSTERED;
			case 68:
				return Capability.GROUP_NON_UNIFORM_QUAD;
			case 69:
				return Capability.SHADER_LAYER;
			case 70:
				return Capability.SHADER_VIEWPORT_INDEX;
			case 71:
				return Capability.UNIFORM_DECORATION;
			case 4165:
				return Capability.CORE_BUILTINS_ARM;
			case 4166:
				return Capability.TILE_IMAGE_COLOR_READ_ACCESS_EXT;
			case 4167:
				return Capability.TILE_IMAGE_DEPTH_READ_ACCESS_EXT;
			case 4168:
				return Capability.TILE_IMAGE_STENCIL_READ_ACCESS_EXT;
			case 4174:
				return Capability.TENSORS_ARM;
			case 4175:
				return Capability.STORAGE_TENSOR_ARRAY_DYNAMIC_INDEXING_ARM;
			case 4176:
				return Capability.STORAGE_TENSOR_ARRAY_NON_UNIFORM_INDEXING_ARM;
			case 4191:
				return Capability.GRAPH_ARM;
			case 4201:
				return Capability.COOPERATIVE_MATRIX_LAYOUTS_ARM;
			case 4212:
				return Capability.FLOAT8EXT;
			case 4213:
				return Capability.FLOAT8_COOPERATIVE_MATRIX_EXT;
			case 4422:
				return Capability.FRAGMENT_SHADING_RATE_KHR;
			case 4423:
				return Capability.SUBGROUP_BALLOT_KHR;
			case 4427:
				return Capability.DRAW_PARAMETERS;
			case 4428:
				return Capability.WORKGROUP_MEMORY_EXPLICIT_LAYOUT_KHR;
			case 4429:
				return Capability.WORKGROUP_MEMORY_EXPLICIT_LAYOUT8_BIT_ACCESS_KHR;
			case 4430:
				return Capability.WORKGROUP_MEMORY_EXPLICIT_LAYOUT16_BIT_ACCESS_KHR;
			case 4431:
				return Capability.SUBGROUP_VOTE_KHR;
			case 4433:
				return Capability.STORAGE_BUFFER16_BIT_ACCESS;
			case 4434:
				return Capability.UNIFORM_AND_STORAGE_BUFFER16_BIT_ACCESS;
			case 4435:
				return Capability.STORAGE_PUSH_CONSTANT16;
			case 4436:
				return Capability.STORAGE_INPUT_OUTPUT16;
			case 4437:
				return Capability.DEVICE_GROUP;
			case 4439:
				return Capability.MULTI_VIEW;
			case 4441:
				return Capability.VARIABLE_POINTERS_STORAGE_BUFFER;
			case 4442:
				return Capability.VARIABLE_POINTERS;
			case 4445:
				return Capability.ATOMIC_STORAGE_OPS;
			case 4447:
				return Capability.SAMPLE_MASK_POST_DEPTH_COVERAGE;
			case 4448:
				return Capability.STORAGE_BUFFER8_BIT_ACCESS;
			case 4449:
				return Capability.UNIFORM_AND_STORAGE_BUFFER8_BIT_ACCESS;
			case 4450:
				return Capability.STORAGE_PUSH_CONSTANT8;
			case 4464:
				return Capability.DENORM_PRESERVE;
			case 4465:
				return Capability.DENORM_FLUSH_TO_ZERO;
			case 4466:
				return Capability.SIGNED_ZERO_INF_NAN_PRESERVE;
			case 4467:
				return Capability.ROUNDING_MODE_RTE;
			case 4468:
				return Capability.ROUNDING_MODE_RTZ;
			case 4471:
				return Capability.RAY_QUERY_PROVISIONAL_KHR;
			case 4472:
				return Capability.RAY_QUERY_KHR;
			case 4473:
				return Capability.UNTYPED_POINTERS_KHR;
			case 4478:
				return Capability.RAY_TRAVERSAL_PRIMITIVE_CULLING_KHR;
			case 4479:
				return Capability.RAY_TRACING_KHR;
			case 4484:
				return Capability.TEXTURE_SAMPLE_WEIGHTED_QCOM;
			case 4485:
				return Capability.TEXTURE_BOX_FILTER_QCOM;
			case 4486:
				return Capability.TEXTURE_BLOCK_MATCH_QCOM;
			case 4495:
				return Capability.TILE_SHADING_QCOM;
			case 4496:
				return Capability.COOPERATIVE_MATRIX_CONVERSION_QCOM;
			case 4498:
				return Capability.TEXTURE_BLOCK_MATCH2QCOM;
			case 5008:
				return Capability.FLOAT16_IMAGE_AMD;
			case 5009:
				return Capability.IMAGE_GATHER_BIAS_LOD_AMD;
			case 5010:
				return Capability.FRAGMENT_MASK_AMD;
			case 5013:
				return Capability.STENCIL_EXPORT_EXT;
			case 5015:
				return Capability.IMAGE_READ_WRITE_LOD_AMD;
			case 5016:
				return Capability.INT64_IMAGE_EXT;
			case 5055:
				return Capability.SHADER_CLOCK_KHR;
			case 5067:
				return Capability.SHADER_ENQUEUE_AMDX;
			case 5087:
				return Capability.QUAD_CONTROL_KHR;
			case 5112:
				return Capability.INT4_TYPE_INTEL;
			case 5114:
				return Capability.INT4_COOPERATIVE_MATRIX_INTEL;
			case 5116:
				return Capability.B_FLOAT16_TYPE_KHR;
			case 5117:
				return Capability.B_FLOAT16_DOT_PRODUCT_KHR;
			case 5118:
				return Capability.B_FLOAT16_COOPERATIVE_MATRIX_KHR;
			case 5249:
				return Capability.SAMPLE_MASK_OVERRIDE_COVERAGE_NV;
			case 5251:
				return Capability.GEOMETRY_SHADER_PASSTHROUGH_NV;
			case 5254:
				return Capability.SHADER_VIEWPORT_INDEX_LAYER_EXT;
			case 5255:
				return Capability.SHADER_VIEWPORT_MASK_NV;
			case 5259:
				return Capability.SHADER_STEREO_VIEW_NV;
			case 5260:
				return Capability.PER_VIEW_ATTRIBUTES_NV;
			case 5265:
				return Capability.FRAGMENT_FULLY_COVERED_EXT;
			case 5266:
				return Capability.MESH_SHADING_NV;
			case 5282:
				return Capability.IMAGE_FOOTPRINT_NV;
			case 5283:
				return Capability.MESH_SHADING_EXT;
			case 5284:
				return Capability.FRAGMENT_BARYCENTRIC_KHR;
			case 5288:
				return Capability.COMPUTE_DERIVATIVE_GROUP_QUADS_KHR;
			case 5291:
				return Capability.FRAGMENT_DENSITY_EXT;
			case 5297:
				return Capability.GROUP_NON_UNIFORM_PARTITIONED_NV;
			case 5301:
				return Capability.SHADER_NON_UNIFORM;
			case 5302:
				return Capability.RUNTIME_DESCRIPTOR_ARRAY;
			case 5303:
				return Capability.INPUT_ATTACHMENT_ARRAY_DYNAMIC_INDEXING;
			case 5304:
				return Capability.UNIFORM_TEXEL_BUFFER_ARRAY_DYNAMIC_INDEXING;
			case 5305:
				return Capability.STORAGE_TEXEL_BUFFER_ARRAY_DYNAMIC_INDEXING;
			case 5306:
				return Capability.UNIFORM_BUFFER_ARRAY_NON_UNIFORM_INDEXING;
			case 5307:
				return Capability.SAMPLED_IMAGE_ARRAY_NON_UNIFORM_INDEXING;
			case 5308:
				return Capability.STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING;
			case 5309:
				return Capability.STORAGE_IMAGE_ARRAY_NON_UNIFORM_INDEXING;
			case 5310:
				return Capability.INPUT_ATTACHMENT_ARRAY_NON_UNIFORM_INDEXING;
			case 5311:
				return Capability.UNIFORM_TEXEL_BUFFER_ARRAY_NON_UNIFORM_INDEXING;
			case 5312:
				return Capability.STORAGE_TEXEL_BUFFER_ARRAY_NON_UNIFORM_INDEXING;
			case 5336:
				return Capability.RAY_TRACING_POSITION_FETCH_KHR;
			case 5340:
				return Capability.RAY_TRACING_NV;
			case 5341:
				return Capability.RAY_TRACING_MOTION_BLUR_NV;
			case 5345:
				return Capability.VULKAN_MEMORY_MODEL;
			case 5346:
				return Capability.VULKAN_MEMORY_MODEL_DEVICE_SCOPE;
			case 5347:
				return Capability.PHYSICAL_STORAGE_BUFFER_ADDRESSES;
			case 5350:
				return Capability.COMPUTE_DERIVATIVE_GROUP_LINEAR_KHR;
			case 5353:
				return Capability.RAY_TRACING_PROVISIONAL_KHR;
			case 5357:
				return Capability.COOPERATIVE_MATRIX_NV;
			case 5363:
				return Capability.FRAGMENT_SHADER_SAMPLE_INTERLOCK_EXT;
			case 5372:
				return Capability.FRAGMENT_SHADER_SHADING_RATE_INTERLOCK_EXT;
			case 5373:
				return Capability.SHADER_SM_BUILTINS_NV;
			case 5378:
				return Capability.FRAGMENT_SHADER_PIXEL_INTERLOCK_EXT;
			case 5379:
				return Capability.DEMOTE_TO_HELPER_INVOCATION;
			case 5380:
				return Capability.DISPLACEMENT_MICROMAP_NV;
			case 5381:
				return Capability.RAY_TRACING_OPACITY_MICROMAP_EXT;
			case 5383:
				return Capability.SHADER_INVOCATION_REORDER_NV;
			case 5390:
				return Capability.BINDLESS_TEXTURE_NV;
			case 5391:
				return Capability.RAY_QUERY_POSITION_FETCH_KHR;
			case 5394:
				return Capability.COOPERATIVE_VECTOR_NV;
			case 5404:
				return Capability.ATOMIC_FLOAT16_VECTOR_NV;
			case 5409:
				return Capability.RAY_TRACING_DISPLACEMENT_MICROMAP_NV;
			case 5414:
				return Capability.RAW_ACCESS_CHAINS_NV;
			case 5418:
				return Capability.RAY_TRACING_SPHERES_GEOMETRY_NV;
			case 5419:
				return Capability.RAY_TRACING_LINEAR_SWEPT_SPHERES_GEOMETRY_NV;
			case 5430:
				return Capability.COOPERATIVE_MATRIX_REDUCTIONS_NV;
			case 5431:
				return Capability.COOPERATIVE_MATRIX_CONVERSIONS_NV;
			case 5432:
				return Capability.COOPERATIVE_MATRIX_PER_ELEMENT_OPERATIONS_NV;
			case 5433:
				return Capability.COOPERATIVE_MATRIX_TENSOR_ADDRESSING_NV;
			case 5434:
				return Capability.COOPERATIVE_MATRIX_BLOCK_LOADS_NV;
			case 5435:
				return Capability.COOPERATIVE_VECTOR_TRAINING_NV;
			case 5437:
				return Capability.RAY_TRACING_CLUSTER_ACCELERATION_STRUCTURE_NV;
			case 5439:
				return Capability.TENSOR_ADDRESSING_NV;
			case 5568:
				return Capability.SUBGROUP_SHUFFLE_INTEL;
			case 5569:
				return Capability.SUBGROUP_BUFFER_BLOCK_IOINTEL;
			case 5570:
				return Capability.SUBGROUP_IMAGE_BLOCK_IOINTEL;
			case 5579:
				return Capability.SUBGROUP_IMAGE_MEDIA_BLOCK_IOINTEL;
			case 5582:
				return Capability.ROUND_TO_INFINITY_INTEL;
			case 5583:
				return Capability.FLOATING_POINT_MODE_INTEL;
			case 5584:
				return Capability.INTEGER_FUNCTIONS2INTEL;
			case 5603:
				return Capability.FUNCTION_POINTERS_INTEL;
			case 5604:
				return Capability.INDIRECT_REFERENCES_INTEL;
			case 5606:
				return Capability.ASM_INTEL;
			case 5612:
				return Capability.ATOMIC_FLOAT32_MIN_MAX_EXT;
			case 5613:
				return Capability.ATOMIC_FLOAT64_MIN_MAX_EXT;
			case 5616:
				return Capability.ATOMIC_FLOAT16_MIN_MAX_EXT;
			case 5617:
				return Capability.VECTOR_COMPUTE_INTEL;
			case 5619:
				return Capability.VECTOR_ANY_INTEL;
			case 5629:
				return Capability.EXPECT_ASSUME_KHR;
			case 5696:
				return Capability.SUBGROUP_AVC_MOTION_ESTIMATION_INTEL;
			case 5697:
				return Capability.SUBGROUP_AVC_MOTION_ESTIMATION_INTRA_INTEL;
			case 5698:
				return Capability.SUBGROUP_AVC_MOTION_ESTIMATION_CHROMA_INTEL;
			case 5817:
				return Capability.VARIABLE_LENGTH_ARRAY_INTEL;
			case 5821:
				return Capability.FUNCTION_FLOAT_CONTROL_INTEL;
			case 5824:
				return Capability.FPGA_MEMORY_ATTRIBUTES_INTEL;
			case 5837:
				return Capability.FP_FAST_MATH_MODE_INTEL;
			case 5844:
				return Capability.ARBITRARY_PRECISION_INTEGERS_INTEL;
			case 5845:
				return Capability.ARBITRARY_PRECISION_FLOATING_POINT_INTEL;
			case 5886:
				return Capability.UNSTRUCTURED_LOOP_CONTROLS_INTEL;
			case 5888:
				return Capability.FPGA_LOOP_CONTROLS_INTEL;
			case 5892:
				return Capability.KERNEL_ATTRIBUTES_INTEL;
			case 5897:
				return Capability.FPGA_KERNEL_ATTRIBUTES_INTEL;
			case 5898:
				return Capability.FPGA_MEMORY_ACCESSES_INTEL;
			case 5904:
				return Capability.FPGA_CLUSTER_ATTRIBUTES_INTEL;
			case 5906:
				return Capability.LOOP_FUSE_INTEL;
			case 5908:
				return Capability.FPGADSP_CONTROL_INTEL;
			case 5910:
				return Capability.MEMORY_ACCESS_ALIASING_INTEL;
			case 5916:
				return Capability.FPGA_INVOCATION_PIPELINING_ATTRIBUTES_INTEL;
			case 5920:
				return Capability.FPGA_BUFFER_LOCATION_INTEL;
			case 5922:
				return Capability.ARBITRARY_PRECISION_FIXED_POINT_INTEL;
			case 5935:
				return Capability.USM_STORAGE_CLASSES_INTEL;
			case 5939:
				return Capability.RUNTIME_ALIGNED_ATTRIBUTE_INTEL;
			case 5943:
				return Capability.IO_PIPES_INTEL;
			case 5945:
				return Capability.BLOCKING_PIPES_INTEL;
			case 5948:
				return Capability.FPGA_REG_INTEL;
			case 6016:
				return Capability.DOT_PRODUCT_INPUT_ALL;
			case 6017:
				return Capability.DOT_PRODUCT_INPUT4X8_BIT;
			case 6018:
				return Capability.DOT_PRODUCT_INPUT4X8_BIT_PACKED;
			case 6019:
				return Capability.DOT_PRODUCT;
			case 6020:
				return Capability.RAY_CULL_MASK_KHR;
			case 6022:
				return Capability.COOPERATIVE_MATRIX_KHR;
			case 6024:
				return Capability.REPLICATED_COMPOSITES_EXT;
			case 6025:
				return Capability.BIT_INSTRUCTIONS;
			case 6026:
				return Capability.GROUP_NON_UNIFORM_ROTATE_KHR;
			case 6029:
				return Capability.FLOAT_CONTROLS2;
			case 6033:
				return Capability.ATOMIC_FLOAT32_ADD_EXT;
			case 6034:
				return Capability.ATOMIC_FLOAT64_ADD_EXT;
			case 6089:
				return Capability.LONG_COMPOSITES_INTEL;
			case 6094:
				return Capability.OPT_NONE_EXT;
			case 6095:
				return Capability.ATOMIC_FLOAT16_ADD_EXT;
			case 6114:
				return Capability.DEBUG_INFO_MODULE_INTEL;
			case 6115:
				return Capability.B_FLOAT16_CONVERSION_INTEL;
			case 6141:
				return Capability.SPLIT_BARRIER_INTEL;
			case 6144:
				return Capability.ARITHMETIC_FENCE_EXT;
			case 6150:
				return Capability.FPGA_CLUSTER_ATTRIBUTES_V2INTEL;
			case 6161:
				return Capability.FPGA_KERNEL_ATTRIBUTESV2INTEL;
			case 6162:
				return Capability.TASK_SEQUENCE_INTEL;
			case 6169:
				return Capability.FP_MAX_ERROR_INTEL;
			case 6171:
				return Capability.FPGA_LATENCY_CONTROL_INTEL;
			case 6174:
				return Capability.FPGA_ARGUMENT_INTERFACES_INTEL;
			case 6187:
				return Capability.GLOBAL_VARIABLE_HOST_ACCESS_INTEL;
			case 6189:
				return Capability.GLOBAL_VARIABLE_FPGA_DECORATIONS_INTEL;
			case 6220:
				return Capability.SUBGROUP_BUFFER_PREFETCH_INTEL;
			case 6228:
				return Capability.SUBGROUP2D_BLOCK_IOINTEL;
			case 6229:
				return Capability.SUBGROUP2D_BLOCK_TRANSFORM_INTEL;
			case 6230:
				return Capability.SUBGROUP2D_BLOCK_TRANSPOSE_INTEL;
			case 6236:
				return Capability.SUBGROUP_MATRIX_MULTIPLY_ACCUMULATE_INTEL;
			case 6241:
				return Capability.TERNARY_BITWISE_FUNCTION_INTEL;
			case 6245:
				return Capability.SPEC_CONDITIONAL_INTEL;
			case 6246:
				return Capability.FUNCTION_VARIANTS_INTEL;
			case 6400:
				return Capability.GROUP_UNIFORM_ARITHMETIC_KHR;
			case 6425:
				return Capability.TENSOR_FLOAT32_ROUNDING_INTEL;
			case 6427:
				return Capability.MASKED_GATHER_SCATTER_INTEL;
			case 6441:
				return Capability.CACHE_CONTROLS_INTEL;
			case 6460:
				return Capability.REGISTER_LIMITS_INTEL;
			case 6528:
				return Capability.BINDLESS_IMAGES_INTEL;
			default:
				throw new RuntimeException(value + "does not map to a valid enum");
		}
	}
}